# ────────────────────────────────────────────────────────────
# Omarchy Felix Theme for Alacritty
# By Ty Richards
# https://github.com/TyRichards
# ────────────────────────────────────────────────────────────

[window]
# window padding {px}
padding.x = 45
padding.y = 40
decorations = "none"

[font]
size = 12.0


[colors]

[colors.normal]
black = "#101618"
red = "#FB6E88"
green = "#48d597"
yellow = "#F5B944"
blue = "#8BA1FF"
magenta = "#DA6177"
cyan = "#788ADD"
white = "#FEFFFF"

[colors.bright]
black = "#1C2225"
red = "#FB6E88"
green = "#48d597"
yellow = "#F5B944"
blue = "#8BA1FF"
magenta = "#DA6177"
cyan = "#788ADD"
white = "#FEFFFF"

[colors.cursor]
cursor = '#48d597'
text = '#080F11'

[colors.primary]
background = '#080F11'
foreground = '#FEFFFF'
dim_foreground = "#788ADD"

[colors.selection]
background = '#2D3048'
text = '#FEFFFF'

[colors.vi_mode_cursor]
text = "#080F11"
cursor = "#48d597"
