general {
    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors

    layout = dwindle
    gaps_in = 0
    gaps_out = 0
    border_size = 1
    col.active_border = rgba(48d597FF)
    col.inactive_border = rgba(1C2225FF)
}

decoration {
    rounding = 6
	  dim_special = 0.0
    active_opacity = 1.0
    inactive_opacity = 0.85
    
    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        # enabled = true
        # size = 8
        # passes = 1
        vibrancy = 0.1696
        #
        enabled = true
        size = 8
        passes = 1
        new_optimizations = true
        xray = false
		    contrast = 0.7
		    brightness = 0.5
		    noise = 0.1
		    # vibrancy = 80
		    vibrancy_darkness = 0.0
		    special = true
    }
}

group {
    col.border_active = rgba(48d597FF)
    col.border_inactive = rgba(1C2225FF)
    # auto_group = true

    groupbar {
        # rounding = 10
        font_family = JetBrainsMono Nerd Font Mono
        font_size = 10
        height = 30
        text_offset = -1
        indicator_gap = 1
        indicator_height = 1
        col.active = rgba(20A36Cff)
        col.inactive = rgba(2D3048FF)
        text_color = rgba(FEFFFFEF)
        text_color_inactive = rgba(788ADDff)
        gaps_in = 0
        gaps_out = 0
        # font_weight_active = bold
        # font_weight_inactive = normal
    }
}
